openshift/openshift-apiserver

pkg/bootstrappolicy/policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Updated the `storage-admin` permissions so that it may view pods. This permission is necessary, as when running `oc describe pvc` we list the pods mounting the PVCs.
This PR resolves [BZ-1727266](https://bugzilla.redhat.com/show_bug.cgi?id=1727266).
This is for OS 4.x.
=> BZ-1727266: Adjusted storage-admin role policy.

pkg/authorization/apis/authorization/types.go, pkg/bootstrappolicy/policy.go, pkg/oauth/apis/oauth/validation/validation_test.go, test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
This removes the actual anonynmous discovery and status access.
Follow-up of https://github.com/openshift/origin/pull/23641.
=> Bug 1711533: auth: remove unauthenticated discovery and status access

Makefile
/assign @tnozicka 
This PR enables supplying a custom image registry to `make images` like so:
`make IMAGE_REGISTRY=quay.io/sallyom images`
see this also: https://github.com/openshift/library-go/pull/556
=> udpate make images target

pkg/bootstrappolicy/namespace_policy.go, test/testdata/bootstrappolicy/bootstrap_namespace_roles.yaml
This role enables authenticated users to be able to read resources from
the "openshift" namespace. For the "motd" feature [1] to work, the role
needs to enable users to read configmaps as well. This PR enables that.
[1] https://github.com/openshift/oc/pull/67
=> Add capability of reading configmaps to shared-resource-viewer role

pkg/version/version.go
This fix the registration of `openshift_apiserver_build_info` which was also renamed.
/cc @deads2k 
/cc @sttts
=> metrics: fix registration and name of version metric

pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
Eventually this should wire the standard option flags through, but for now simply removing the side-channel option is enough.
=> remove side-channel wiring for cluster authentication

pkg/cmd/openshift-apiserver/cmd.go, pkg/cmd/openshift-apiserver/openshiftapiserver/config.go, pkg/cmd/openshift-apiserver/server.go
Exposes generic API server authentication and authorization flags to CLI so that they can be used by a hosted deployment of the openshift API server.
=> Wire generic API server authentication and authorization flags

pkg/image/apiserver/registryhostname/environmentresolvercache_test.go
Use "::1/128" instead of 127.0.0.1
=> Use IPv6 in resolver cache tests

pkg/build/apiserver/registry/buildconfiginstantiate/rest.go
per discussions today with @bparees and @ricardomaraschini 
@openshift/openshift-team-developer-experience FYI
/assign @bparees
=> Bug 1795705: return actual instantiate error for binary builds

pkg/bootstrappolicy/constants.go, pkg/bootstrappolicy/policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
The system:registry cluster role in 4.x is managed by cluster-image-registry-operator
https://github.com/openshift/cluster-image-registry-operator/blob/a925d0e2ac596b393a29b808a51607a36db15f4d/pkg/resource/clusterrole.go#L44
This PR is to avoid problems when the same object is managed by two controllers.
=> Remove system:registry cluster role

pkg/build/apiserver/admission/strategyrestrictions/admission.go, pkg/build/apiserver/admission/strategyrestrictions/helpers.go, pkg/build/apiserver/admission/strategyrestrictions/helpers_test.go, pkg/template/apiserver/registry/templateinstance/helpers.go, pkg/template/apiserver/registry/templateinstance/helpers_test.go, pkg/template/apiserver/registry/templateinstance/strategy.go
See https://coreos.slack.com/archives/CB48XQ4KZ/p1588008887095400 for history
/assign @deads2k 
@deads2k - I could not find any official guideline on how to (a presumably temporary until a rebase pulls it in) copy of k8s in lieu of vendoring; please advise if code changes / commit wording etc. need modification
/assign @dmage 
@dmage if possible minimally pls make sure this change catches your instance of the problem
@openshift/openshift-team-developer-experience @bparees  FYI
/hold
since the upstream PR https://github.com/kubernetes/kubernetes/pull/90534  has not merged yet ... however, if during review we think it is just a matter of when I'll unhold
=> Bug 1731222: unwarranted SARs on foreground GC of objects with owner refs

pkg/bootstrappolicy/controller_policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Manual cherry-pick of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/394
/assign @deads2k
=> [release-4.4] Bug 1829327: allow patch for updating namespace

pkg/bootstrappolicy/all_test.go, pkg/bootstrappolicy/constants.go, pkg/bootstrappolicy/policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
We want to be able to add them permissions to read/write snapshots. Since volume snapshots are based on CRDs, those rules will be added in csi-snapshot-controller-operator. See https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/39
=> Bug 1841035: Modify basic-user and storage-admin to be aggregated

pkg/bootstrappolicy/controller_policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Manual cherry-pick of openshift/cluster-kube-controller-manager-operator#394 & https://github.com/openshift/openshift-apiserver/pull/100
/assign @deads2k
=> [release-4.3] Bug 1829328: allow patch for updating namespace

pkg/api/serialization_test.go, pkg/build/apis/build/v1/conversion.go, pkg/build/apis/build/v1/conversion_test.go, pkg/build/apis/build/v1/register.go
Adding a manual conversion func to create BinaryBuildRequestOptions from
url query parameters. This is an attempt to address some of the issues in #95 that prevent the 1.19 rebase.
Before I go down the rabbit hole of reflection APIs, I want to make sure that this is generally the right thing to do for this situation. The test case converts url query parameters to a `BinaryBuildRequestOptions`, which exists to ensure `oc start-build` works properly.
=> Bug 1844479: Add custom conversion for binary builds 

pkg/image/apiserver/importer/importer.go, pkg/image/apiserver/importer/importer_test.go
When importing a manifest list only one manifest is imported therefore
we need to use this one manifest digest instead of the digest for the
whole manifest list when checking for integrity.
=> Bug 1751258: Using manifest digest on manifest list import

pkg/image/OWNERS
Adding the team that owns the image API to OWNERS.
=> Add image registry team to pkg/image OWNERS

pkg/bootstrappolicy/policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
openshift-ingress (aka router) is switching to endpointslices.
Related PRs:
- https://github.com/openshift/cluster-ingress-operator/pull/426
- https://github.com/openshift/cluster-ingress-operator/pull/428
- https://github.com/openshift/router/pull/154
=> Update system:router cluster role for endpointslices

pkg/image/apiserver/importer/importer.go, pkg/image/apiserver/importer/metrics.go
This commit adds a new metric: a counter of attempts to import images from registries using protocol v1. This protocol version has been deprecated in the past but before we remove its support from apiserver we need to be sure nobody is using it.
A PrometheusRule will be created to alert on top of this counter, as we don't have any Prometheus rule on this repository it will be created on Image Registry operator project (we already have other rules related to Image Registries in there).
=> IR-99: Adding metric for registry v1 protocol imports

pkg/image/apis/image/test/conversion_test.go, pkg/image/apis/image/v1/conversion.go
Implemented manual conversions for TagEvent and TagEventCondition
slices.
Related to PR https://github.com/openshift/openshift-apiserver/pull/95
=> Bug 1844495: TagEvent and TagEventCondition conversions

pkg/image/apis/image/v1/conversion.go
Adding manual conversions (back and forth) for types:
```
docker10.DockerConfig <-> dockerpre012.DockerConfig
docker10.DockerImage  <-> dockerpre012.DockerImage
```
Related to PR https://github.com/openshift/openshift-apiserver/pull/95
=> Bug 1844495: Added manual conversions for DockerImage type

pkg/image/apiserver/importer/importer.go
When user does not provide a registry docker.io is used by default. By
calling DockerClientDefaults() we assure that we always have it properly
set.
=> Bug 1861696: Using DockerClientDefaults on block/insecure check

pkg/bootstrappolicy/controller_policy.go, pkg/bootstrappolicy/dead.go, test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
The cluster role and binding for the ingress-to-route controller will be managed by the openshift-controller-manager operator.
* `pkg/bootstrappolicy/controller_policy.go` (`InfraIngressToRouteControllerServiceAccountName`): Delete constant.
(`init`): Delete the `system:openshift:controller:ingress-to-route-controller` cluster role.
* `pkg/bootstrappolicy/dead.go` (`init`): Add entries for the `system:openshift:controller:ingress-to-route-controller` cluster role and cluster role binding.
* `test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml`:
* `test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml`: Regenerate.
----
See https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/169.
=> Bug 1820075: Delete policy for ingress-to-route-controller

pkg/build/apiserver/buildgenerator/generator.go, pkg/build/apiserver/buildgenerator/generator_test.go
Label check should allow underscores, hyphens, and decimals in the name
instead of restricting to DNS RFC 1123 compatible values
=> Bug 1862532: Fix label value validation for BuildConfigs

pkg/build/apis/build/validation/s2i_validation.go, pkg/build/apis/build/validation/validation_test.go
Turns our we do not vendor in openshift/source-to-image, but copy some of its packages into openshift/openshift-apiserver
Assuming there is a rationale / history on that, and am not going to bother altering the apporach.
So I'm porting our recent fix ohttps://github.com/openshift/source-to-image/commit/129c90e36fec88dae5e2910a0de4082836e1b623
/assign @adambkaplan
=> Bug 1884270: bypass golang url parsing with scp styled ssh git URLs; refactor URL for older git clients

go.mod, go.sum, vendor/k8s.io/client-go/transport/cache.go, vendor/modules.txt
we will carry a patch that allows the client to detect broken connections to the api server more quickly than the default TCP timeout of 15 minutes.
this patch will be dropped in future releases once http2/ping is introduced.
=> pin to github.com/openshift/kubernetes-client-go

pkg/apps/apiserver/registry/instantiate/rest.go
`DeploymentConfig` kind is registered under `v1` in the scheme. Registration happens here https://github.com/openshift/openshift-apiserver/blob/e75d326783d96501e0904dfd787eca4fc08b900a/pkg/apps/apis/apps/v1/register.go#L15
When calling a webhook we need to specify the version explicitly otherwise the kind won't be found in the registry and the requests will fail with `no kind "DeploymentConfig" is registered for version "apps.openshift.io/" in scheme`
It seems this was the only place it was broken. Feel free to double-check that.
=> Bug 1867380: When using webhooks in OCP 4.5 fails to rollout latest deploymentconfig

pkg/bootstrappolicy/policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
The oc code which added jobs, cronjobs and statefulset is in https://github.com/openshift/oc/pull/671
/assign @sttts
=> Bug 1915661: update image-pruner role to include jobs, cronjobs and statefulsets

pkg/bootstrappolicy/controller_policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
oc/idle is now updating the service in addition to the endpoints when
idling.
Related PRs:
- https://github.com/openshift/openshift-controller-manager/pull/165
- https://github.com/openshift/oc/pull/720
- https://github.com/openshift/router/pull/225
- https://github.com/openshift/sdn/pull/252
=> Bug 1900989: policy/unidling-controller: allow get/update on services

pkg/bootstrappolicy/policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Upstream started leveraging .well-known endpoints and only allows
serviceaccounts to access them by default. Limit
basic-user access to the `/.well-known/oauth-authorization-server`
endpoint that is needed for authentication into OpenShift.
Counter-part in kube-apiserver: https://github.com/openshift/kubernetes/pull/615
cc @deads2k @sttts
=> limit basic-user cluster role well-known access to oauth-authorization-server only

pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
ShutdownDelayDuration allows to block shutdown for some time, e.g. until endpoints pointing to this API server
have converged on all node. During this time, the API server keeps serving, /healthz will return 200, but /readyz will return failure. This is important for the graceful shutdown.
=> sets shutdown-delay-duration from OpenShiftAPIServerConfig

go.mod, go.sum, vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagereferencemutators/pods.go, vendor/github.com/openshift/apiserver-library-go/pkg/apivalidation/uservalidation.go, vendor/modules.txt
Allows to include ':' in usernames if prepended by 'b64'.
This is to allow creating identities/users whose IdP-side
identifier contains either ':' or '/'. These are base64-encoded
and the result is appended after the 'b64:' tag in the object
name.
cc @sttts @deads2k
=> bump apiserver-lib-go for looser username validation

pkg/client/impersonatingclient/impersonate.go
The authorization.openshift.io RBAC proxy is taking values from
the Extra field of a UserInfo of a user that made a request against
this API. The fields of the map may generally contain values that
cannot appear in an HTTP header, like '/' that's commonly separating
an API annotation from the API version or resource.
Copy the k8s.io header escaping function and use it in the proxy
that's handling the OpenShift authorization API.
/cc @s-urbaniak @sttts 
/cherry-pick release-4.7
=> Bug 1972383: openshift authorization proxy: escape header key values

.ci-operator.yaml, go.mod, go.sum, images/Dockerfile.rhel, pkg/apps/apiserver/registry/deploylog/wait_test.go
Basically revert of https://github.com/openshift/openshift-apiserver/pull/220 now that .ci-operator.yaml is active.
=> Bump to Golang 1.16

.gitignore, pkg/build/apis/build/validation/validation.go, pkg/build/apis/build/validation/validation_test.go
Validate the secret name and configMap name to provide a better user
experience when creating a build config that contains buildVolumes
Also, updating .gitignore to ignore _output directory that is not
cleaned up after running make verify
=> Bug 1978627: Validate secret name and configMap name

pkg/build/apis/build/validation/s2i_validation.go, pkg/build/apis/build/validation/validation_test.go
we were just wrong with https://github.com/openshift/openshift-apiserver/pull/147
/assign @adambkaplan 
note with the redhat outage tests will fail, even unit (as there is an attempt to access registry.access.redhat.com in one of the tests)
=> Bug 1971332: revert incorrect ssh scp fix

pkg/route/apiserver/admission/requiredrouteannotations/admission.go, pkg/route/apiserver/admission/requiredrouteannotations/admission_test.go
Routes without TLS should just be admitted if they are missing HSTS annotation in a domain that requires HSTS annotation.
Error messages should have more information.
=> Bug 1990826: routes without TLS are rejected for missing HSTS annotation

pkg/build/apiserver/registry/buildconfiginstantiate/rest.go
When `Build` fails during `buildconfiginstantiate` (binary build), `status.reason`
and `status.message` are taken from the older state of the `Build` object, and they
are empty.
Must be taken from the new object obtained from `watch`.
=> Bug 1977414: return correct reason and message from failed build

pkg/build/apiserver/buildgenerator/generator.go, pkg/build/apiserver/buildgenerator/generator_test.go
https://github.com/openshift/openshift-controller-manager/pull/201 is the more critical of the changes but I thought these changes were still useful for posterity
/assign @adambkaplan 
/assign @alicerum
=> Bug 2004203: no longer abort ICT induced builds because of spec last triggered image ID

go.mod, go.sum, vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/accept.go, vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go, vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go, vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go, vendor/modules.txt
This is a backport of #259 to address the [bug 2022188](https://bugzilla.redhat.com/show_bug.cgi?id=2022188).
**Impact:** Resolution of image stream names in deployment configs does not work because the image policy plugin does not know about them.
**Cause:** The problem exists since the beginning, but it wasn't visible as the image policy plugin used to resolve image streams names in all pods. Once we've fixed the [bug 1925180](https://bugzilla.redhat.com/show_bug.cgi?id=1925180), the plugin doesn't update controlled objects anymore, i.e. it doesn't update pods that are created for the deployment config.
**Resolution:** Update the admission plugin so that is aware of deployment configs.
=> Bug 2022188: Image policy should mutate DeploymentConfigs

pkg/project/auth/cache.go, pkg/project/auth/cache_test.go
The auth cache of the projects storage implementation did not lock its data. This is most likely the source why projects sometimes did not show up, a bug we have heard from customers for long long time.
All credits to @davidfestal for finding this through his kcp work.
=> projects: add rw mutex to auth cache

pkg/project/printers/internalversion/printer.go
we see a panic when we are deep copying `TableRow` of `Project` type:
```
2022-01-27T15:02:37.171735296Z E0127 15:02:37.171633       1 runtime.go:76] Observed a panic: cannot deep copy core.NamespacePhase
```
We can trace it back to here:
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/deepcopy.go#L33
and then here:
https://github.com/kubernetes/kubernetes/blob/9968b0eff06f109792e64f37ee92889711713a88/staging/src/k8s.io/apimachinery/pkg/runtime/converter.go#L639
`Project.Status.Phase` is a `core.NamespacePhase` type, and `DeepCopyJSONValue` will panic if it is a type alias, it needs to be a string.
Now, why we didn't see this error before, I have not been able to find out yet.
=> Bug 2047335: fix panic from printer

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go, vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go, vendor/modules.txt
This PR bumps library-go to get a new registryclient that can correctly
handle image references like
registry.example.com/namespace.with.dot/foo
=> Bug 2049234: Fix importing images that have dots in their namespace

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go, vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go, vendor/modules.txt
Backport of #279.
This PR bumps library-go to get a new registryclient that can correctly
handle image references like
registry.example.com/namespace.with.dot/foo
=> Bug 2053218: Fix importing images that have dots in their namespace

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go, vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go, vendor/modules.txt
Backport of #282.
This PR bumps library-go to get a new registryclient that can correctly
handle image references like
registry.example.com/namespace.with.dot/foo
=> Bug 2053223: Fix importing images that have dots in their namespace

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/crypto/missing_san.go, vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go, vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go, vendor/modules.txt
Backport of #281.
This PR bumps library-go to get a new registryclient that can correctly
handle image references like
registry.example.com/namespace.with.dot/foo
=> Bug 2053222: Fix importing images that have dots in their namespace

images/Dockerfile.rhel
backport of https://github.com/openshift/openshift-apiserver/pull/277
ref https://issues.redhat.com/browse/ART-3664
/assign tkashem
=> [release-4.8][ART-3664] Bug 2043808: IPs with leading zeros are still valid in the apiserver

images/Dockerfile.rhel
backport of https://github.com/openshift/openshift-apiserver/pull/280
ref https://issues.redhat.com/browse/ART-3664
=> [release-4.7][ART-3664] Bug 2043804: IPs with leading zeros are still valid in the apiserver

pkg/route/apis/route/types.go, pkg/route/apis/route/v1/conversion.go, pkg/route/apis/route/validation/validation.go, pkg/route/apis/route/validation/validation_test.go, pkg/route/apiserver/registry/route/strategy.go, pkg/route/apiserver/registry/route/strategy_test.go
When a subdomain field is set, and host is unset, allow host to be empty.
---
This is https://github.com/openshift/openshift-apiserver/pull/194, rebased for https://github.com/openshift/openshift-apiserver/pull/210 and https://github.com/openshift/openshift-apiserver/pull/248.
I had planned to add `ValidateSubdomain` with https://github.com/openshift/library-go/pull/1240 and use that in this PR, but I got mired in a go-mod morass, gave up, and added a to-do comment to use use library-go in the future.
=> NE-882: Allow route subdomains to be omitted

images/Dockerfile.rhel
ref https://issues.redhat.com/browse/ART-3664
backport of [#287](https://github.com/openshift/openshift-apiserver/pull/287)
=> [release-4.6][ART-3664] Bug 2043805: IPs with leading zeros are still valid in the apiserver

pkg/project/auth/cache.go, pkg/project/auth/cache_test.go
The project authorization cache is invalidated when either the set of
clusterrole resource versions or clusterrolebinding resource versions
has changed since the previous invalidation test. The last observed
resourceversion sets are stored in fields of the cache struct for use
on the following invocation.
After computing the resource version set for clusterroles, the same
string set is cleared and repopulated with the clusterrolebinding
resource version set. Since the set's underlying type is a reference
type (map), both the clusterrole and the clusterrolebinding saved sets
point to the same map containing only clusterrolebinding resource
versions. The effect in practice is that every tick of synchronize
involves a full cache invalidation.
=> Stop unnecessary project auth cache invalidations.

pkg/image/apiserver/registry/imagestreamtag/imagestreamregistry_test.go, pkg/image/apiserver/registry/imagestreamtag/imagestreamregistrytester.go, pkg/image/apiserver/registry/imagestreamtag/rest.go, pkg/image/apiserver/registry/imagestreamtag/rest_test.go
Adding retry during update to address test failures
https://search.ci.openshift.org/?search=.*Operation+cannot+be+fulfilled+on+imagestreamtags.*&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.12-e2e-aws-sdn-serial/1548438013934047232
: [sig-imageregistry][Feature:ImageTriggers][Serial] ImageStream API TestImageStreamTagLifecycleHook [Suite:openshift/conformance/serial]
Message: "Operation cannot be fulfilled on imagestreamtags.image.openshift.io \"test\": the object has been modified; please apply your changes to the latest version and try again",
Investigation indicated that the test was not specifying a particular …
=> add retry on imagestreamtag update

pkg/security/apiserver/registry/podsecuritypolicyselfsubjectreview/rest_test.go
The printf analyzer flags this as an error and fails to build in later
Go 1.18 releases due to this change:
https://go-review.googlesource.com/c/tools/+/340409/5/go/analysis/passes/printf/printf.go.
=> Remove use of %w formatting directive from t.Errorf call.

pkg/route/apis/route/validation/validation.go, pkg/route/apis/route/validation/validation_test.go
To allow for reuse on variants serving routes via CRD, convert from
internal to v1 types and validate those. The v1 validation logic will
then be able to move to a library, where it can be shared without any
dependencies on openshift-apiserver.
=> Make route validation operate on v1 types.

pkg/route/apiserver/admission/routehostassignment/assignment.go, pkg/route/apiserver/admission/routehostassignment/assignment_test.go, pkg/route/apiserver/registry/route/etcd/etcd_test.go, pkg/route/apiserver/registry/route/strategy.go
The eventual goal is to handle host assignment via admission plugins in order to share one implementation between apiserver- and CRD-based routes. In this phase, the relevant functions and tests are moved with only necessary changes.
=> Move route host assignment code out of the route REST strategy.

pkg/project/auth/cache.go, pkg/project/auth/cache_test.go
This reverts commit a0312dfd20d114fd36af80196c1873389530e784.
Clusters with high namespace and RBAC counts exhibit very long (~minutes) project auth cache sync times. On such clusters, project list requests are effectively unavailable due to time spent waiting to acquire the project auth cache lock.
```
goroutine 9646202 [semacquire, 3 minutes]:
sync.runtime_SemacquireMutex(0x0?, 0x98?, 0xc0097c7260?)
runtime/sema.go:71 +0x25
sync.(*RWMutex).RLock(...)
sync/rwmutex.go:63
github.com/openshift/openshift-apiserver/pkg/project/auth.(*AuthorizationCache).List(0xc000437040, {0x47c9070, 0xc02cdc4c40}, {0x47cf848, 0x639d800})
github.com/openshift/openshift-apiserver/pkg/project/auth/cache.go:486 +0x9a
github.com/openshift/openshift-apiserver/pkg/project/apiserver/registry/project/proxy.(*REST).Lis …
```
=> OCPBUGS-2803: Revert "projects: add rw mutex to auth cache"

pkg/project/auth/cache.go, pkg/project/auth/cache_test.go
Backport of https://github.com/openshift/openshift-apiserver/pull/326 to 4.11.
This reverts commit a0312dfd20d114fd36af80196c1873389530e784.
Clusters with high namespace and RBAC counts exhibit very long (~minutes) project auth cache sync times. On such clusters, project list requests are effectively unavailable due to time spent waiting to acquire the project auth cache lock.
=> [release-4.11] OCPBUGS-2809: Revert "projects: add rw mutex to auth cache"

pkg/bootstrappolicy/controller_policy.go, pkg/bootstrappolicy/policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
after https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/270 merges, this will remove the old so we don't end up with conflict content.
=> move the deployer role and binding to the ocm-o

pkg/project/apis/project/validation/validation.go, pkg/project/apis/project/validation/validation_test.go
When a new label with non-empty value is added to a project, validation error will occur due to missing label is mistaken as a label with empty string value.
The fix is to verify if the label exists before comparing its value.
Signed-off-by: Vu Dinh <vudinh@outlook.com>
=> OCPBUGS-7689: Fix a project validation error due to empty string value

go.mod, go.sum, vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml, vendor/github.com/openshift/api/operator/v1/types_network.go, vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go, vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go, vendor/github.com/openshift/api/route/v1/generated.proto, vendor/github.com/openshift/api/route/v1/route.crd.yaml, vendor/github.com/openshift/api/route/v1/route.crd.yaml-patch, vendor/github.com/openshift/api/route/v1/stable.route.testsuite.yaml, vendor/github.com/openshift/api/route/v1/types.go, vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go, vendor/modules.txt
Bump openshift/api for `route.spec.tls.insecureEdgeTerminationPolicy` documentation fix showing incorrect usage.
To achieve the bump, I ran the following commands:
```
go get github.com/openshift/api@v0.0.0-20230509100629-894b49f57a15
go mod tidy
go mod vendor
```
API Bump: https://github.com/openshift/api/pull/1438
=> OCPBUGS-11393: Bump openshift/api

.gitignore, pkg/cmd/openshift-apiserver/openshiftapiserver/config.go, pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go, pkg/cmd/openshift-apiserver/server.go
skip default openapi installation for the apiserver aggregator. As a result of this, we can remove `delegatedAPIServer.RemoveOpenAPIData()` call in v2 aggregation controller.
similar change is being pushed into oauth-apiserver as well (https://github.com/openshift/oauth-apiserver/pull/89)
TBD:
We should remove this [commit](https://github.com/openshift/kubernetes-apiserver/commit/47b6b17b9fbc958510f1d854574573e068c4b210) from carry list on k8s-apiserver in future rebase
=> wire openapi v3 aggregation controller

pkg/cmd/openshift-apiserver/openshiftapiserver/config.go, pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go, pkg/image/apiserver/apiserver.go, pkg/image/apiserver/registry/imagestreamimport/rest.go
story card: [OCPNODE-1448](https://issues.redhat.com/browse/OCPNODE-1448)
This PR is a part of code migration to use ImageDigestMirrorSet API. 
The [OCPNODE-521](https://issues.redhat.com//browse/OCPNODE-521) will land new CRDs for image mirror configurations 4.13.
The current components rely on ICSP and should use new APIs in future release.
- Epic to keep track of ICSP migrations for openshift components: https://issues.redhat.com/browse/OCPNODE-1258    
- ImageDigestMirrorSet implemented: openshift/machine-config-operator#3037 
- ImageDigestMirrorSet epic: https://issues.redhat.com/browse/OCPNODE-521
=> [OCPNODE-1448] idms migrations

pkg/cmd/openshift-apiserver/openshiftapiserver/config.go, pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
Extend the OA init code to explicitly disable individual apiservers. The change is important for explicitly disabling DeploymentConfigs and Builds API through capabilities. The controlplane configuration on-disk data type gets rendered by OA operator in https://github.com/openshift/cluster-openshift-apiserver-operator/pull/532.
=> WRKLDS-728: Disable apiservers

go.mod, go.sum, vendor/k8s.io/apiserver/pkg/server/options/feature.go, vendor/k8s.io/apiserver/pkg/server/options/recommended.go, vendor/k8s.io/apiserver/pkg/server/options/server_run_options.go, vendor/modules.txt
pulls https://github.com/openshift/kubernetes-apiserver/pull/55 
doesn't require any changes because the config is created "manually" - https://github.com/openshift/openshift-apiserver/blob/master/pkg/cmd/openshift-apiserver/openshiftapiserver/config.go#L58 and the apf is never enabled (even if the flag says so)
=> NO-ISSUE: go mod tidy && go mod vendor

pkg/bootstrappolicy/policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
Remove UnauthenticatedGroup from:
- SelfAccessReview
- OAuthTokenDelete
- WebHooksRole
- ScopeImpersonation
An unauthenticated User should have no permissions.
=> AUTH-509: remove unauthenticated group from any cluster role binding

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/route/validation/validation.go, vendor/modules.txt
Bump  https://github.com/openshift/library-go/commit/e22d25af55872cb4e4cbaef1e7d45ebf1d2dad5f
To reduce error message details for Not Found secret inside `validateTLSExternalCertificate()`
Vendors https://github.com/openshift/library-go/pull/1735
Fixes [OCPBUGS-33574](https://issues.redhat.com//browse/OCPBUGS-33574)
=> OCPBUGS-33574: Bump library-go

go.mod, go.sum, vendor/modules.txt
no vendored files changed but we bump anyway to prevent potential future imports of packages affected by CVE-2024-3727.
this change will not be backported.
=> OCPBUGS-42215: bump containers/image to v5.24.3

pkg/cmd/openshift-apiserver/openshiftapiserver/config.go, pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go, pkg/image/apis/image/types.go, pkg/image/apis/image/v1/defaults.go
As per https://github.com/openshift/enhancements/pull/1605, there was a
new field introduced in the image config spec and status which reflects
the global value to be set for imagestream import mode which is behind a
featuregate. This PR reads the observed config, checks if the importmode
string is present and uses it as the default when creating imagestreams.
API changes: https://github.com/openshift/api/pull/1928
cluster-openshift-apiserver-operator changes: https://github.com/openshift/cluster-openshift-apiserver-operator/pull/582
image-registry-operator changes: https://github.com/openshift/cluster-image-registry-operator/pull/109
=> MULTIARCH-4558: Set default for imagestreamImportMode based on observed config changes in the image config

pkg/image/apiserver/importer/importer.go
in our ci we are seeing a series of panics being generated when we attempt to import some images. it is not clear yet how we end up with a missing image together with a nil error.
this pr introduces a check, similar to what has been done for https://issues.redhat.com/browse/OCPBUGS-35036, this new check logs the occurence and reports the error back using the cluster resource.
this is what panic trace:
```
2025-01-09T13:15:39.559789879Z E0109 13:15:39.559758       1 audit.go:84] "Observed a panic" panic=<
2025-01-09T13:15:39.559789879Z >runtime error: invalid memory address or nil pointer dereference
2025-01-09T13:15:39.559789879Z >goroutine 451090 [running]:
2025-01-09T13:15:39.559789879Z >k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1.1() …
```
=> OCPBUGS-45861: prevent panic when no image and error are set

pkg/image/apiserver/importer/importer.go
if we fail to process a given tag or digest we should move to the next and not return. if we "prematurely" return we may cause some of the tags or digest have their Image pointer nulled, possibly causing a panic.
=> OCPBUGS-45861: move on to the next digest/tag during failures

pkg/image/apiserver/importer/importer.go, pkg/image/apiserver/importer/importer_test.go
Do not return the blocked error as with the NeverContactSource configuration from IDMS ITMS, the image is not considered blocked. While the actual source from the image specification is blocked when the source gets redirected to the mirrors.
Create the ITMS setting NeverContactSource
```yaml
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
name: tag-mirror
spec:
imageTagMirrors:
- mirrors:
- quay.io
source: foo.io
mirrorSourcePolicy: NeverContactSource
```
import an image from the source, no blocked error returned
```
$ oc import-image imgstream --from=foo.io/qiwanredhat/busybox:latest --confirm
imagestream.image.openshift.io/imgstream imported
Name:			imgstream
Namespace:		default
Created:		Less than a second ago
Labels:			<none>
Annotations: …
```
=> OCPBUGS-44432: Skip blocked registry check for registries with mirrors

pkg/image/apiserver/importer/import_integration_test.go
quay.io/coreos/etcd:latest is gone, use a different tag instead
=> OCPBUGS-54458: Fix image reference in TestImageStreamImportQuayIO

pkg/image/apiserver/admission/limitrange/admission.go, pkg/image/apiserver/importer/importer.go, pkg/image/apiserver/internal/imageutil/helpers.go, pkg/image/apiserver/internal/imageutil/helpers_test.go, pkg/image/apiserver/internalimageutil/helpers.go, pkg/image/apiserver/registry/image/strategy.go, pkg/image/apiserver/registry/imagestream/registry.go, pkg/image/apiserver/registry/imagestream/strategy.go, pkg/image/apiserver/registry/imagestreamimage/rest.go, pkg/image/apiserver/registry/imagestreamimport/imagecreater.go, pkg/image/apiserver/registry/imagestreamimport/rest.go, pkg/image/apiserver/registry/imagestreammapping/rest.go, pkg/image/apiserver/registry/imagestreammapping/rest_test.go, pkg/image/apiserver/registry/imagestreamtag/rest.go, pkg/image/apiserver/registry/imagetag/rest.go
Some of API servers that run in openshift-apiserver do not support dry run (like Image). So that when user passes `--dry-run=server` in oc for image related resources (as described in the linked issue), it actually performs the operation instead of simulating the operation and outputs the result. This is unwanted and disruptive behavior that may lead to undesired consequences. 
The reason of the issue is dry-run option is not wired through the storage layer of Image. This PR tries to achieve this.
=> OCPBUGS-35855: Wire dry run option to Image API server operations

LICENSE
This change adds the Apache 2.0 License file from: https://github.com/openshift/api/blob/master/LICENSE
This aligns openshift-apiserver with other repos in the project to clearly designate this as Apache 2.0 Licensed Software.
Other projects already have this License file:
https://github.com/openshift/cluster-version-operator/blob/main/LICENSE
https://github.com/openshift/cluster-network-operator/blob/master/LICENSE
https://github.com/openshift/oauth-apiserver/blob/master/LICENSE
=> NO-JIRA: Add Apache 2.0 License file

go.mod, go.sum, vendor/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go, vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go, vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/factory.go, vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/retry_etcdprobemonitor.go, vendor/modules.txt
https://github.com/openshift/kubernetes-apiserver/pull/70
https://github.com/openshift/kubernetes-apiserver/pull/58
Edit: Ignore the branch name on my remote. It's a bump of our apiserver fork, not library-go.
=> [release-4.17] OCPBUGS-61584: Bump openshift/kubernetes-apiserver for etcd retry patches.
