openshift/openshift-apiserver

Dockerfile
Dockerfile.rhel

images: fix the path from which the binary is being built

---

vendor/github.com/getsentry/raven-go/Dockerfile.test
vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/cmd/oc/main.go
vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/cmd/openshift/main.go
vendor/k8s.io/kubernetes/third_party/etcd.BUILD

/cc @sttts 
/cc @deads2k 
for doing the bump :)

Fix vendor

---

pkg/apps/apis/apps/validation/validation.go
pkg/apps/apis/apps/validation/validation_test.go

one piece of openshift/origin#22683
/cc @soltysh

Fix DC latestVersion validation

---

pkg/project/auth/cache.go

project/auth/cache: add more context to errors

---

pkg/image/apis/image/validation/fake/fake.go
pkg/image/apis/image/validation/validation.go
pkg/image/apis/image/validation/validation_test.go
pkg/image/apis/image/validation/whitelist/whitelister.go
pkg/image/apis/image/validation/whitelist/whitelister_test.go

This PR enables tests for whitelister.

Allow new images from a referenced repository

---

pkg/build/apiserver/buildgenerator/generator.go
pkg/build/apiserver/registry/buildconfiginstantiate/rest.go

@openshift/openshift-team-developer-experience FYI
/assign @bparees

Bug 1795705: increase error logging around apiserver binary build flow

---

pkg/image/apiserver/registry/imagestreamimport/rest.go

This change stems from a problem determination session that @dmage , @sdodson , and I had with a disconnected customer recently, and the difficulty in getting at the root cause of the customer's problem (which was a config error on their part).
The flow was:
- sample stream imports failed as expected going to registry.redhat.io
- customer changed the sample registry config to a mirrored repo, but the necessary config so that the image registry could communicate with that mirrored repo was not in place
- since the type/status/reason did not change with the new import error, the status condition was not bumped and when everyone looked at the imagestream status conditions, it looked like the sample registry config change did not take hold
- where if the message was considered, it would have …

Bug 1788700: include ISI error message changes when determining new generation need

---

pkg/build/apiserver/registry/buildconfiginstantiate/rest.go

Ref: https://github.com/openshift/api/pull/626#discussion_r408285340
/assign @adambkaplan

Buildconfig: Check emptyness of buildRequest.TriggedBy via len

---

pkg/template/apiserver/registry/template/rest_test.go

fix for https://github.com/openshift/openshift-apiserver/pull/95

Bug 1830887: fix test scheme for templates

---

pkg/apps/apiserver/registry/rollback/rollback_generator.go

fixes runtime.Object copies in rollbackgenerator.
This also fixes part of https://github.com/openshift/openshift-apiserver/pull/95

Bug 1830887: fix the rollback generator scheme usage

---

pkg/project/apiserver/registry/projectrequest/delegated/delegated.go

Before:
> Internal error occurred: the server could not find the requested resource
After:
> Internal error occurred: user.openshift.io/v1, Kind=Group is not namespace-scoped

Bug 1843496: project: improve error message on cluster-scoped template objects

---

pkg/apps/apis/apps/v1/conversion.go

I've verified this on top of https://github.com/openshift/openshift-apiserver/pull/95.
/assign @deads2k @sttts

Bug 1844485: fix apps conversions

---

pkg/apps/apis/apps/v1/conversion.go
pkg/apps/apis/apps/v1/register.go
pkg/apps/apis/apps/v1/zz_generated.conversion.go

Bug 1877363: fix missing conversions for DeploymentLogOptions

---

pkg/build/apiserver/registry/build/strategy.go
pkg/build/apiserver/registry/build/strategy_test.go
pkg/build/apiserver/registry/buildconfig/strategy.go
pkg/build/apiserver/registry/buildconfig/strategy_test.go

Updating to set metadata.generation on create, and increment metadata.generation on update
Added tests for create/update metadata.generation

Bug 1866605: metadata.generation not getting set/updated

---

pkg/api/serialization_test.go
pkg/image/apis/image/dockerpre012/conversion.go
pkg/image/apis/image/v1/conversion.go
pkg/image/apis/image/v1/zz_generated.conversion.go
vendor/k8s.io/apimachinery/pkg/conversion/converter.go
vendor/k8s.io/apimachinery/pkg/runtime/scheme.go
vendor/k8s.io/code-generator/cmd/conversion-gen/generators/conversion.go

preview of https://github.com/kubernetes/kubernetes/pull/94480
The only impact appears to be imagestreams.
/assign @dmage

checking conversions for upstream changes.

---

go.mod
pkg/image/apiserver/importer/image.go
pkg/image/apiserver/importer/importer.go
pkg/image/apiserver/internalimageutil/helpers.go
pkg/image/apiserver/registry/imagestream/etcd/image.go
vendor/github.com/docker/distribution/manifest/ocischema/builder.go
vendor/github.com/docker/distribution/manifest/ocischema/manifest.go
vendor/modules.txt

OCI Schema support for image stream imports.

IR-113: OCI Schema support for ImageStream import

---

go.mod
go.sum
vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
vendor/k8s.io/apiserver/pkg/server/config.go
vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
vendor/k8s.io/apiserver/pkg/server/filters/wrap.go
vendor/modules.txt

to pick up openshift/kubernetes-apiserver#20

bumps kubernetes-apiserver 

---

pkg/image/apiserver/registry/imagestream/strategy.go

The API server shouldn't modify CacheableObjects as their encoded representation may already be cached. Instead the API server should populate all necessary fields when it creates objects as is already doing for dockerImageRepository.
See also https://github.com/kubernetes/kubernetes/blob/b7fc3f91ea64eff4be673449e08df581eeddf42c/pkg/registry/core/service/storage/storage.go#L128-L143

Bug 1912590: Populate publicDockerImageRepository for new image streams

---

go.sum

Not sure how these got left in the go.sum, might need to add some additional validations

Cleaning up some leftover packages

---

pkg/cmd/openshift-apiserver/openshiftadmission/plugin_initializer.go

Expose Route and Config informers on the InformerAccess interface.

expose config and route informers on informeraccess interface

---

pkg/route/apis/route/validation/validation.go
pkg/route/apis/route/validation/validation_test.go

Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1964112
A matrix regarding the alignment with the router can be found [here](https://docs.google.com/spreadsheets/d/16bY_SCk9hYQJE3G54y8WBk_nG2RWd5hMc3n1efc50YQ/edit#gid=0) 
The fix ensures alignment with the router if the annotation AllowNonDNSCompliantHostAnnotation is set to "false".
It enables the exact same validation mechanism as set in the openshift/router [here](https://github.com/openshift/router/blob/master/pkg/router/controller/unique_host.go#L240) 
To override this functionality set the annotation AllowNonDNSCompliantHostAnnotation to "true".
Validation steps :
Created 4.8.0 cluster (cluster-bot) with current PR
Deployed simple echo pod and service
Create Valid Route
- No annotations
- Name "poc-demo-test"
- curl -k …

Bug 1964112: Fix for host name validation error

---

pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go

There should be only one source of truth for creation of openshift-infra namespace. This is introduced in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/570

remove creation of openshift-infra namespace

---

pkg/image/apiserver/admission/imagepolicy/originimagereferencemutators/meta.go

OriginImageMutators provides the method GetAnnotationAccessor which returns an accessor that should be aware of origin objects. This change makes it provide access to template annotations of deployment configs and other origin objects.

Bug 2032589: Make OriginImageMutators aware of origin objects

---

images/Dockerfile.rhel

ref https://issues.redhat.com/browse/ART-3664

Bug 2043807: add deprecated parser build flag

---

pkg/image/OWNERS

pkg/image: add myself to OWNERS

---

pkg/route/apis/route/validation/validation.go
pkg/route/apiserver/registry/route/strategy.go
pkg/route/apiserver/registry/route/strategy_test.go

IOUs from https://github.com/openshift/openshift-apiserver/pull/382
/assign @p0lyn0mial 
/cc @thejasn

add comments about ownership of validation

---

pkg/image/apiserver/importer/importer.go
pkg/image/apiserver/importer/importer_manifestlist_test.go

When trying to import two images with the same digest but different import mode, the code will currently bug out and import both images as Legacy. Using the import mode in the manifest cache key solves the problem.

OCPBUGS-16514: use import mode to manifest cache key

---

go.mod
go.sum
vendor/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
vendor/modules.txt

Pulls in https://github.com/openshift/kubernetes/pull/1681 and https://github.com/openshift/kubernetes/pull/1676 via https://github.com/openshift/kubernetes-apiserver/pull/51

OCPBUGS-27094: UPSTREAM: <carry>: retry etcd Unavailable errors 

---

pkg/quota/apiserver/registry/clusterresourcequota/strategy.go

OCPBUGS-22301: make GarbageCollection supported for ClusterResourceQuotas as it is backed by a CRD

---

go.mod
go.sum
vendor/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/factory.go
vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/retry_etcdprobemonitor.go
vendor/modules.txt

a proof for https://github.com/openshift/kubernetes-apiserver/pull/58

NO-JIRA: UPSTREAM: <carry>: retrying etcd Unavailable errors for the etcd health and ready checkers

---

pkg/image/apiserver/importer/importer.go
pkg/image/apiserver/importer/importer_test.go

I still can't wrap my head around what situation(s) could cause this state where both the image and the error are nil.
To try and unblock CI folks, I solved the panic without addressing the root cause, since I haven't been able to trace it. To help us understand this state in the future, the code now also logs some extra information when it hits the state that previously caused the panic to happen.

OCPBUGS-35036: fail image import when both image and error are nil 

---

pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go

alternative to https://github.com/openshift/kubernetes-apiserver/pull/59

NO-JIRA: apiserver: sanitize the generic config for the chained servers

---

pkg/image/apiserver/importer/importer.go

even though we do not expect these two properties to be nil (Image and Err) we better check them to avoid having panics if something changes in the future.
this pr introduces the same guardrails used in two different parts of the code: makes sure we have at least one of `Err` or `Image` properties set.

OCPBUGS-45861: validate image property isn't nil before using

---

.ci-operator.yaml
go.mod
images/Dockerfile.rhel
pkg/build/apiserver/registry/buildconfiginstantiate/rest.go
pkg/image/apiserver/registry/imagestreammapping/rest_test.go
pkg/template/apiserver/registry/template/rest.go

Reworking https://github.com/openshift/openshift-apiserver/pull/529 with some updates needed to pass the verify job.

OCPBUGS-57858: Updating ose-openshift-apiserver-container image to be consistent with ART for 4.20
